### ISSUE TITLE
Connection to MHO-C401 not possible

### ISSUE THREAD

**Issue by Flugente-19** [OzzyCzech/MHO-C401#1]
Hello OzzyCzech,

I have tried to use your Python scripts to connect to my MHO-C401 device, but without success. The scripts have been started from a Raspberry Pi with Python 3.7.3 according to your guide https://ozzyczech.cz/iot/read-temperature-and-huminidy-from-mho-c401. Here is the output of the script **list-services.py** with corrected MAC address of my device:
```
pi@xxxxxxxx:~/BT $ python3 list-services.py
Connecting to device...
Traceback (most recent call last):
  File "list-services.py", line 6, in <module>
    for service in device.getServices():
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 481, in getServices
    return self.services
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 477, in services
    self._serviceMap = self.discoverServices()
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 459, in discoverServices
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 14, error: Request attribute has encountered an unlikely error)
pi@xxxxxxxx:~/BT $
```
Do you have an idea why it is not working? My MHO-C401 seems to work properly. I can read the temperature and the humidity using an ESP32 with Tasmota 9.1.0 without any issues.

Second question: I have seen, that you don't need the encryption key to read the temperature and the humidity. How is it possible? I think, the connection is encrypted.

Thank you in advance!

Kind regards
Flugente-19

**Comment by Flugente-19** [comment]
Hello,

Today I have checked the scripts on Raspberry Pi 4B with two new devices LYWSD03MMC and MHO-C401. They are working properly.

I don't found the reason for the previous issue.

Kind regards
Flugente-19

**Comment by OzzyCzech** [comment]
Thanks for information

**Comment by turbidWaters** [comment]
@Flugente-19  Can you help me with getting it to work on tasmota, on a esp32? I have the tasmota32-bluetooth.bin release 11.0.0 installed on a sonoff dual r3. Sorry to use this thread for tasmota.
